export const azureUserColumns = [
	{ name: 'id', type: 'string' },
	{ name: 'xata.createdAt', type: 'datetime' },
	{ name: 'xata.updatedAt', type: 'datetime' },
	{ name: 'xata.version', type: 'string' },
	...[
		{ name: 'accountEnabled', type: 'bool' },
		{ name: 'ageGroup', type: 'string' },
		{ name: 'businessPhones', type: 'multiple' },
		{ name: 'city', type: 'string' },
		{ name: 'createdDateTime', type: 'datetime' },
		{ name: 'department', type: 'string' },
		{ name: 'displayName', type: 'string' },
		{ name: 'givenName', type: 'string' },
		{ name: 'lastPasswordChangeDateTime', type: 'datetime' },
		{ name: 'mail', type: 'email' },
		{ name: 'mailNickname', type: 'string' },
		{ name: 'mobilePhone', type: 'string' },
		{ name: 'onPremisesDistinguishedName', type: 'string' },
		{ name: 'onPremisesSamAccountName', type: 'string' },
		{ name: 'onPremisesSyncEnabled', type: 'bool' },
		{ name: 'postalCode', type: 'string' },
		{ name: 'streetAddress', type: 'string' },
		{ name: 'surname', type: 'string' },
		{ name: 'userType', type: 'string' },
		{ name: 'onPremisesLastSyncDateTime', type: 'datetime' },
	],
] as const;
